### ISSUE TITLE
Switch license from LGPL to Apache

### ISSUE THREAD

**Issue by adamgreen** [adamgreen/mri#11]
I have had a request to change MRI away from the LGPL license to something more permissive. I would like to switch it to Apache. 

@JaredCJR @jserv  Do you have any issue with the license on your contributions being switched to use an Apache license?

**Comment by JaredCJR** [comment]
@adamgreen 
I think that's fine!

**Comment by jserv** [comment]
Agree. Please do.

**Comment by adamgreen** [comment]
Thanks guys! I will make this change soon.

**Comment by adamgreen** [comment]
Switch completed and pushed to master.
