### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by g40** [adamgreen/mri#2]
Hello Adam - apologies, this is probably not the optimal way to reach out and ask questions. But presumably the same principle would apply to an NXP43XX series or indeed one of the mbed enabled Freescale K64F devices?

**Comment by adamgreen** [comment]
@g40 I recently added support for the LPC4330 based Micromint Bambino 210 board to MRI.  This forced me to fill in the missing FPU register support as well.  I wrote up some porting notes based on this work which can be found here: https://github.com/adamgreen/mri/blob/master/notes/mri-porting.creole#mri-porting
