### ISSUE TITLE
armv7-m and armv8-m are similar in debug module structure, whether it is possible to use the same set of codes, and then use macros to control armv7-m or armv8-m

### ISSUE THREAD

**Issue by anjiahao1** [adamgreen/mri#37]
I used the existing armv7-m code on armv8-m. So far, I found that there is no difference in use except that the register order of DWT_COMP is different, so we can use macros to distinguish whether to use armv7-m or armv8-m, and then use armv7-m code? Or rewrite a arch of support for armv8-m?

**Comment by adamgreen** [comment]
My recommendation would be to do whatever is easiest for you at this point in time and dogfood it for awhile. If things look good then you can submit a PR for me to review and then we can come up with a final plan.
