### ISSUE TITLE
Add some integration guide without gcc4mbed to the README

### ISSUE THREAD

**Issue by JaredCJR** [adamgreen/mri#7]
I think most of people would like to use mri without gcc4mbed,so I write some guides here hoping that could be add to the README for people who want to using mri could pick it up more quickly!
- Makefile variable relative to mri
  - add the `$MRI_FLAGS` to the `CFLAGS`
  - add `$MRI_libraries` to the object files lists to `link with the final executable file`

```
# MRI paths  
MRI_ROOT_DIR:=/path/to/the/mri
MRI_LIB_DIR:=$(MRI_ROOT_DIR)/lib/armv7-m
MRI_libraries:=$(MRI_LIB_DIR)/libmri_stm32f429-disco.a

# MRI variable
MRI_ENABLE?=1
DEVICE_MRI_ENABLE:=$(MRI_ENABLE)
MRI_BREAK_ON_INIT?=0
MRI_UART?=MRI_UART_2 
MRI_INIT_PARAMETERS?=$(MRI_UART)

MRI_FLAGS:=\
        -DMRI_ENABLE=$(DEVICE_MRI_ENABLE) \
        -DMRI_INIT_PARAMETERS='"$(MRI_INIT_PARAMETERS)"' \
        -DMRI_BREAK_ON_INIT=$(MRI_BREAK_ON_INIT)
```
- Initialization C code
  - Place the code in the proper place.
  - In default,mri will configure the NVIC,USART,MPU and other debug monitor relative registers(including DWT and FPB)
    - debug monitor interrupt priority must higher than all external interrupts.
    - internal exception handlers will be direct to `mriFaultHandler` or `__mriExceptionHandler`.

``` C
    if (MRI_ENABLE)                                                                            
    {
        __mriInit(MRI_INIT_PARAMETERS);
        if (MRI_BREAK_ON_INIT)
            __debugbreak();
    }
```

Thanks!

**Comment by adamgreen** [comment]
Most users of MRI (all but 1 that I know of) utilize the gcc4mbed makefiles to integrate this debug monitor into their projects.
